// Code generated by "stringer -type BloomUpdateType"; DO NOT EDIT.

package wire

import "strconv"

const _BloomUpdateType_name = "UpdateNoneUpdateAllUpdateP2PubKeyOnly"

var _BloomUpdateType_index = [...]uint8{0, 10, 19, 37}

func (i BloomUpdateType) String() string {
	if i >= BloomUpdateType(len(_BloomUpdateType_index)-1) {
		return "BloomUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BloomUpdateType_name[_BloomUpdateType_index[i]:_BloomUpdateType_index[i+1]]
}
